server:
  port: 8080
  mode: debug
supabase:
  url: https://qikgxznkkokmsypdcysu.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpa2d4em5ra29rbXN5cGRjeXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjYyNzM5NTYsImV4cCI6MjA0MTg0OTk1Nn0.dym6wnoEqb7FQcghh8jgCcRgRsaK-9EeUTmJ_NO7NZU
